# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vi--6QB2DVP1O-q-lDjXZJc1EWpZmX2w
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('baseball.csv')

df.head()